export const AcceptedChatLists = [
  {
    id: 1,
    name: "Tianah Blessing",
    avatar: "/assets/images/Rusty.jpg",
    message: "😰 Lorem ipsum",
    time: "11:31",
    online: true,
    read: true,
    isAccepted: true,
  },
  {
    id: 2,
    name: "John Doe",
    avatar: "/assets/images/Rusty.jpg",
    message: "👋 See you tomorrow",
    time: "10:42",
    online: true,
    read: true,
    isAccepted: true,
    unreadCount: 2,
  },
  {
    id: 3,
    name: "Sarah Williams",
    avatar: "/assets/images/Rusty.jpg",
    message: "😰 Thanks!",
    time: "09:18",
    online: false,
    read: false,
    isAccepted: true,
    unreadCount: 5,
  },
  {
    id: 6,
    name: "David Wilson",
    avatar: "/assets/images/Rusty.jpg",
    message: "😊 Got it",
    time: "07:56",
    online: true,
    read: true,
    isAccepted: true,
  },
  {
    id: 7,
    name: "Olivia Davis",
    avatar: "/assets/images/Rusty.jpg",
    message: "😰 Lorem ipsum",
    time: "07:31",
    online: false,
    read: true,
    isAccepted: true,
  },
  {
    id: 8,
    name: "James Anderson",
    avatar: "/assets/images/Rusty.jpg",
    message: "👋 I'll get back to you",
    time: "07:15",
    online: true,
    read: false,
    isAccepted: true,
  },
  {
    id: 9,
    name: "Sophia Martinez",
    avatar: "/assets/images/Rusty.jpg",
    message: "😊 Thank you",
    time: "06:48",
    online: false,
    read: false,
    isAccepted: true,
  },
  {
    id: 10,
    name: "Daniel Thompson",
    avatar: "/assets/images/Rusty.jpg",
    message: "😰 Please check this",
    time: "06:22",
    online: true,
    read: true,
    isAccepted: true,
  },
];

export const NotAcceptedChatLists = [
  {
    id: 4,
    name: "Michael Brown",
    avatar: "/assets/images/Rusty.jpg",
    message: "👋 See you soon",
    time: "08:45",
    online: true,
    read: false,
    isAccepted: false,
  },
  {
    id: 5,
    name: "Emily Johnson",
    avatar: "/assets/images/Rusty.jpg",
    message: "😊 Thanks!",
    time: "08:12",
    online: false,
    read: false,
    isAccepted: false,
  },
];
